name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Print Hello
      run: echo "Hello from GitHub Actions!"

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Create a test file
      run: echo "This file was created by GitHub Actions on $(date)" > test_output.txt

    - name: Commit file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add test_output.txt
        git commit -m "Add test_output.txt via GitHub Actions" || echo "No changes to commit"

    - name: Push changes to repo
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
        branch: main
